#SET @NEW_MYSQL_USER='dummyuser';
#SET @NEW_MYSQL_USER_PASSWORD='dummypasswd';
#SET @NEW_MYSQL_USER_HOST='localhost';

# SELECT @NEW_MYSQL_USER;
# SELECT @NEW_MYSQL_USER_PASSWORD;
# SELECT @NEW_MYSQL_USER_HOST;

SET @DROP_NEW_USER_IF_EXISTS = CONCAT
('DROP USER IF EXISTS "',@NEW_MYSQL_USER,'"@"',@NEW_MYSQL_USER_HOST,'" ');
PREPARE DROP_NEW_USER_STMT FROM @DROP_NEW_USER_IF_EXISTS;
EXECUTE DROP_NEW_USER_STMT;
DEALLOCATE PREPARE DROP_NEW_USER_STMT;

SET @CREATE_NEW_USER = CONCAT
('CREATE USER "',@NEW_MYSQL_USER,'"@"',@NEW_MYSQL_USER_HOST,'" IDENTIFIED BY "',@NEW_MYSQL_USER_PASSWORD,'" ');
PREPARE CREATE_USER_STMT FROM @CREATE_NEW_USER;
EXECUTE CREATE_USER_STMT;
DEALLOCATE PREPARE CREATE_USER_STMT;

#select user,host,password from mysql.user;
FLUSH PRIVILEGES;
