#SET @ALTER_MYSQL_USER='dummyuser';
#SET @ALTER_MYSQL_USER_HOST='localhost';

# SELECT @ALTER_MYSQL_USER;
# SELECT @ALTER_MYSQL_USER_HOST;

SET @DROP_USER_IF_EXISTS = CONCAT
('DROP USER IF EXISTS "',@ALTER_MYSQL_USER,'"@"',@ALTER_MYSQL_USER_HOST,'" ');
PREPARE DROP_USER_STMT FROM @DROP_USER_IF_EXISTS;
EXECUTE DROP_USER_STMT;
DEALLOCATE PREPARE DROP_USER_STMT;
FLUSH PRIVILEGES;
# SELECT user,host,password from mysql.user;
