# SET @ALTER_MYSQL_USER='dummyuser';
# SET @ALTER_MYSQL_USER_HOST='localhost';
# SET @ALTER_MYSQL_USER_GRANTS='SELECT, ALTER';
# SET @DB_NAME_LOCAL='dummydb';

# SELECT @ALTER_MYSQL_USER;
# SELECT @ALTER_MYSQL_USER_HOST;
# SELECT @ALTER_MYSQL_USER_GRANTS;
# SELECT @DB_NAME;

SET @GRANT_USER_PRIVILEGES = CONCAT
('GRANT ',@ALTER_MYSQL_USER_GRANTS,' ON ',@DB_NAME,'.* TO ',@ALTER_MYSQL_USER,'@',@ALTER_MYSQL_USER_HOST,' ');
PREPARE GRANT_STMT FROM @GRANT_USER_PRIVILEGES;
EXECUTE GRANT_STMT;
DEALLOCATE PREPARE GRANT_STMT;

#select user,host,password from mysql.user;
FLUSH PRIVILEGES;
