#SET @ALTER_MYSQL_USER='dummyuser';
#SET @ALTER_MYSQL_USER_PASSWORD='dummypasswd';
#SET @ALTER_MYSQL_USER_HOST='localhost';
# SELECT @ALTER_MYSQL_USER;
# SELECT @ALTER_MYSQL_USER_PASSWORD;
# SELECT @ALTER_MYSQL_USER_HOST;

SET @ALTER_USER = CONCAT
('ALTER USER ',@ALTER_MYSQL_USER,'@',@ALTER_MYSQL_USER_HOST,' IDENTIFIED BY "',@ALTER_MYSQL_USER_PASSWORD,'" ');
PREPARE ALTER_USER_STMT FROM @ALTER_USER;
EXECUTE ALTER_USER_STMT;
DEALLOCATE PREPARE ALTER_USER_STMT;

#select user,host,password from mysql.user;
FLUSH PRIVILEGES;
